version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: moviereviewdb
      POSTGRES_USER: host
      POSTGRES_PASSWORD: 61305
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DB_NAME: moviereviewdb
      DB_USER: host
      DB_PWD: 61305
      DB_HOST: postgres
      DB_PORT: 5432
      SECRET_KEY: django-insecure-nma=xi6x2p-crjg^ifqqkapyu1qjd0l=+wn)-rijk_o%$!k3w_
    ports:
      - "8888:8000"
    depends_on:
      - postgres
    volumes:
      - .:/backend
    tty: true

volumes:
  postgres_data:
